services:
  fake-front:
    build: ./fake-front
    container_name: fake-gov-mock
    ports:
      - "8889:80"
    depends_on:
      - verifier
    volumes:
      - ./fake-front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fake-front/index.html:/usr/share/nginx/html/index.html

  legit-front:
    build: ./legit-front
    container_name: legi-gov-mock
    ports:
      - "8888:80"
    depends_on:
      - verifier
    volumes:
      - ./legit-front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./legit-front/index.html:/usr/share/nginx/html/index.html

  verifier:
    build: ./verifier
    container_name: verifier
    ports:
      - "8000:8000"
    volumes:
      - ./verifier/:/verifier
