services:
  fake-front:
    build: ./fake-front
    container_name: fake-gov-mock
    ports:
      - "8889:80"
    volumes:
      - ./fake-front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fake-front/index.html:/usr/share/nginx/html/index.html
      - ./legit-front/script.js:/usr/share/nginx/html/script.js
      - ./legit-front/styles.css:/usr/share/nginx/html/styles.css

  legit-front:
    build: ./legit-front
    container_name: legi-gov-mock
    ports:
      - "8888:80"
    volumes:
      - ./legit-front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./legit-front/index.html:/usr/share/nginx/html/index.html
      - ./legit-front/script.js:/usr/share/nginx/html/script.js
      - ./legit-front/styles.css:/usr/share/nginx/html/styles.css

  mobywatel:
    build: ./mObywatel
    container_name: mObywatel
    ports:
      - "7777:80"
    volumes:
      - ./mObywatel/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mObywatel/index.html:/usr/share/nginx/html/index.html
      - ./mObywatel/script.js:/usr/share/nginx/html/script.js
      - ./mObywatel/styles.css:/usr/share/nginx/html/styles.css

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    command: ["./entrypoints/api.sh"]
